import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { First } from 'react-bootstrap/esm/PageItem';
// import { fetchChartData } from './chartsAPI';

const initialState = {
  chartData: [],
  status: ''
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount) => {
//     const response = await fetchCount(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   }
// );
export const fetchChartData = createAsyncThunk('charts/fetchCharts', async () => {
  const response = fetch('https://s3-ap-southeast-1.amazonaws.com/he-public-data/chart2986176.json')
  .then(resp => resp.json())
  .then(json => {
    // console.log(json);
    return json;
  });
  return response;
});
// const 
const chartTransformed = (data) => {
  const chartTransformed = [];
    data.forEach(item => {
      let newObj = {};
      if(item.type === 'Bar') {
        newObj = {
          type: item.type.toLowerCase(),
          x: Array.from({length: item.elements.length}, (_, i) => i + 1),
          y: [...item.elements],
          // marker:{
          //   color: ['rgba(204,204,204,1)', 'rgba(222,45,38,0.8)', 'rgba(204,204,204,1)', 'rgba(204,204,204,1)', 'rgba(204,204,204,1)', 'rgba(204,204,204,1)']
          // }
          values: []
        }
      } else {
        newObj = {
          type: item.type.toLowerCase(),
          values: [...item.elements],
          labels: [...item.elements],
          y:[]
        }
      }

      chartTransformed.push(newObj);
    });
    
    return chartTransformed;
}

export const chartsSlice = createSlice({
  name: 'charts',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    updateData: (state, action) => {
      console.log('action', action, state);
      state.chartData = [...action.payload];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchChartData.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchChartData.fulfilled, (state, action) => {
        console.log('state', action.payload);
        state.status = 'done';
        state.chartData = chartTransformed([...action.payload]);
      });
  },
});

export const {  updateData } = chartsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectChartData = ({charts}) => charts.chartData;


export const updateChart = ({chartIndex, valueIndex, value}) => (dispatch, getState) => {
  let currentValue = [...selectChartData(getState())];
  let update = currentValue[chartIndex];

  if(update.type === 'bar') {
    
  let y = [...update.y];
  y[valueIndex] = parseInt(value);
  console.log('value Y',update, y );
  update = {...update, y};

  } else {
    let val = [...update.values];
    val[valueIndex] = parseInt(value);
    update = {...update, values: val};

  }
  currentValue[chartIndex] = update;
  console.log( 'current',currentValue);

    dispatch(updateData(currentValue));
  
};

export default chartsSlice.reducer;
